"""Write the sarah-weekly-update skill file to ~/.claude/skills/sarah-weekly-update/skill.md"""
import os

dest_dir  = os.path.expanduser('~/.claude/skills/sarah-weekly-update')
dest_file = os.path.join(dest_dir, 'skill.md')
os.makedirs(dest_dir, exist_ok=True)

content = r'''---
name: sarah-weekly-update
description: Generates Sarah Price's National Team Weekly Update .docx from uploaded performance report and Gemini meeting notes. Extracts all content, writes a populated Word document to ~/Downloads/, and confirms when done.
user-invocable: true
---

# National Team Weekly Update Generator

## How to use each week

1. Open a **new Claude Code conversation** (keeps token usage low)
2. Type `/sarah-weekly-update` — Claude will ask you for your two files
3. Upload them and confirm, then Claude generates the Word document and saves it to `~/Downloads/`

Open the file, review, edit as needed, and send.

---

## Instructions for Claude

### Step 0 — Check for uploaded documents

Before doing anything else: look at this conversation and check whether the user has already uploaded their two weekly documents (performance/analytics report AND Gemini meeting notes).

**If either document is missing**, ask:
> To generate this week's update, I need two files:
> 1. **Performance report** — the weekly analytics (page views, articles, property breakdown, cluster stats)
> 2. **Gemini meeting notes** — the transcript or notes from Tuesday's national team meeting
>
> Please upload both and I'll generate the document right away.

Wait for both files before proceeding.

**Once both are uploaded**, proceed to Step 1.

---

### Step 1 — Extract these values

Read both documents carefully and extract:

**DATE**: The week-end or meeting date. Format: "Month D, YYYY" (e.g. "April 14, 2026").

**Stats table** (4 cells):
- `TOTAL_PVS`: total page views with + if approximate (e.g. "366,000+")
- `DATE_RANGE`: label for cell 1 line 2 (e.g. "Page Views · Apr 1–6")
- `ARTICLES`: article count as a string (e.g. "347")
- `PROPERTIES`: property count as a string (e.g. "9")
- `ACHIEVEMENT`: short milestone callout if present (e.g. "YTD Best 6-Day Start"), or empty string

**Cluster Performance Highlights** — exactly 3 bullets, no sub-headers:
Write 3 plain sentences from the performance report. Do NOT use sub-headers like "Engagement Leaders" or "Property Breakdown" — just write the insight as a bullet. Include numbers where available. Combine related points to stay at exactly 3.
(`PERF_1`, `PERF_2`, `PERF_3`)

**Changes table** — one row per item from the meeting notes (max 5):
Each row: `(STATUS, description)` — STATUS must be exactly one of: STOP, FLAG, NEW, TRACKING. Description: 1–2 plain sentences. Pad to 5 rows with `("", "")` if fewer than 5 items.
(`CHANGE_ROWS`)

**Active Test Performance** — exactly 3 bullets:
Plain sentences from meeting notes. Combine where needed to stay at 3. Specific and outcome-focused.
(`ACTIVE_1`, `ACTIVE_2`, `ACTIVE_3`)

**CSA & Tooling Updates** — 2 to 3 bullets:
One distinct item per bullet. Use 3 only if a third item is clearly present.
(`CSA_1`, `CSA_2`, `CSA_3` — optional)

**Action items** — one row per action (max 4):
`(owner, action, timing)` — timing is "This week", "Ongoing", or a specific date.
(`ACTION_ROWS`)

---

### Step 2 — Generate and run the Python script

Using the values you extracted, write a complete Python script to `~/.claude/skills/sarah-weekly-update/weekly_build.py`. Then run it with `python3`.

The script must follow this exact structure — substitute all extracted values in place of the `<<<PLACEHOLDER>>>` markers:

```python
"""Auto-generated by /sarah-weekly-update skill."""
from docx import Document
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import os

TEMPLATE = os.path.expanduser('~/.claude/skills/sarah-weekly-update/Template National Team Weekly Update.docx')
OUT      = os.path.expanduser('<<<OUT_PATH>>>')

doc  = Document(TEMPLATE)
body = doc.element.body
XML_SPACE = '{http://www.w3.org/XML/1998/namespace}space'

def make_run(text, size_pt, color_hex, bold=False):
    r = OxmlElement('w:r')
    rPr = OxmlElement('w:rPr')
    fonts = OxmlElement('w:rFonts')
    fonts.set(qn('w:ascii'), 'Arial')
    fonts.set(qn('w:hAnsi'), 'Arial')
    rPr.append(fonts)
    for tag in ('w:sz', 'w:szCs'):
        el = OxmlElement(tag)
        el.set(qn('w:val'), str(int(size_pt * 2)))
        rPr.append(el)
    col = OxmlElement('w:color')
    col.set(qn('w:val'), color_hex)
    rPr.append(col)
    if bold:
        rPr.append(OxmlElement('w:b'))
    r.append(rPr)
    t = OxmlElement('w:t')
    t.set(XML_SPACE, 'preserve')
    t.text = text
    r.append(t)
    return r

def make_linebreak():
    r = OxmlElement('w:r')
    r.append(OxmlElement('w:br'))
    return r

def clear_runs(para_elem):
    for r in list(para_elem):
        if r.tag == qn('w:r'):
            para_elem.remove(r)

def set_para(para_elem, text, size_pt, color_hex, bold=False):
    clear_runs(para_elem)
    para_elem.append(make_run(text, size_pt, color_hex, bold))

def set_cell(cell, run_specs):
    p = cell.paragraphs[0]._element
    clear_runs(p)
    for i, (text, size_pt, color_hex, bold) in enumerate(run_specs):
        if i > 0:
            p.append(make_linebreak())
        p.append(make_run(text, size_pt, color_hex, bold))

def set_stats_cell(cell, number, label):
    p0 = cell.paragraphs[0]._element
    clear_runs(p0)
    p0.append(make_run(number, 13, '2E75B6', False))
    p1 = cell.paragraphs[1]._element
    clear_runs(p1)
    p1.append(make_run(label, 8.5, '555555', False))

def set_stats_cell_single(cell, text):
    p0 = cell.paragraphs[0]._element
    clear_runs(p0)
    p1 = cell.paragraphs[1]._element
    clear_runs(p1)
    p1.append(make_run(text, 8.5, '555555', False))

def make_para_elem(text, size_pt, color_hex, bold=False, bullet=False):
    p = OxmlElement('w:p')
    pPr = OxmlElement('w:pPr')
    if bullet:
        numPr = OxmlElement('w:numPr')
        ilvl  = OxmlElement('w:ilvl');  ilvl.set(qn('w:val'),  '0')
        numId = OxmlElement('w:numId'); numId.set(qn('w:val'), '1')
        numPr.append(ilvl); numPr.append(numId)
        pPr.append(numPr)
        ind = OxmlElement('w:ind')
        ind.set(qn('w:left'),    '560')
        ind.set(qn('w:hanging'), '280')
        pPr.append(ind)
    spacing = OxmlElement('w:spacing')
    spacing.set(qn('w:before'),   '40')
    spacing.set(qn('w:after'),    '40')
    spacing.set(qn('w:line'),     '240')
    spacing.set(qn('w:lineRule'), 'auto')
    pPr.append(spacing)
    p.append(pPr)
    p.append(make_run(text, size_pt, color_hex, bold))
    return p

def replace_with_paras(placeholder_elem, para_specs):
    cursor = placeholder_elem
    for spec in para_specs:
        text, size_pt, color_hex, bold = spec[0], spec[1], spec[2], spec[3]
        bullet = spec[4] if len(spec) > 4 else False
        new_p = make_para_elem(text, size_pt, color_hex, bold, bullet)
        cursor.addnext(new_p)
        cursor = new_p
    placeholder_elem.getparent().remove(placeholder_elem)

date_para          = body[1]
perf_placeholder   = body[4]
active_placeholder = body[8]
csa_placeholder    = body[10]
footer_para        = body[14]
stats_tbl   = doc.tables[0]
changes_tbl = doc.tables[1]
actions_tbl = doc.tables[2]

# 1. Date
set_para(date_para, '<<<DATE>>>', 9.5, '777777')

# 2. Stats table
row0 = stats_tbl.rows[0]
set_stats_cell(row0.cells[0], '<<<TOTAL_PVS>>>', '<<<DATE_RANGE>>>')
set_stats_cell(row0.cells[1], '<<<ARTICLES>>>', 'Articles Published')
set_stats_cell(row0.cells[2], '<<<PROPERTIES>>>', 'Properties')
set_stats_cell_single(row0.cells[3], '<<<ACHIEVEMENT>>>')

# 3. Cluster Performance Highlights — 3 bullets, no sub-headers
replace_with_paras(perf_placeholder, [
    ('<<<PERF_1>>>', 9.5, '000000', False, True),
    ('<<<PERF_2>>>', 9.5, '000000', False, True),
    ('<<<PERF_3>>>', 9.5, '000000', False, True),
])

# 4. Changes table
change_rows = <<<CHANGE_ROWS>>>
for i, (status, desc) in enumerate(change_rows):
    if i >= len(changes_tbl.rows):
        break
    row = changes_tbl.rows[i]
    if status:
        set_cell(row.cells[0], [(status, 9.5, 'FFFFFF', True)])
    if desc:
        set_cell(row.cells[1], [(desc, 9.5, '000000', False)])

# 5. Active Test Performance — 3 bullets
replace_with_paras(active_placeholder, [
    ('<<<ACTIVE_1>>>', 9.5, '000000', False, True),
    ('<<<ACTIVE_2>>>', 9.5, '000000', False, True),
    ('<<<ACTIVE_3>>>', 9.5, '000000', False, True),
])

# 6. CSA & Tooling Updates
csa_bullets = <<<CSA_BULLETS>>>
replace_with_paras(csa_placeholder, [
    (b, 9.5, '000000', False, True) for b in csa_bullets
])

# 7. Action items
action_rows = <<<ACTION_ROWS>>>
for i, (owner, action, timing) in enumerate(action_rows):
    if i + 1 >= len(actions_tbl.rows):
        break
    row = actions_tbl.rows[i + 1]
    set_cell(row.cells[0], [(owner,  9.0, '000000', False)])
    set_cell(row.cells[1], [(action, 9.0, '000000', False)])
    set_cell(row.cells[2], [(timing, 9.0, '000000', False)])

# 8. Footer
for t in footer_para.findall('.//' + qn('w:t')):
    if t.text and 'National Team Weekly' in t.text:
        t.text = f"National Team Weekly  \u00b7  <<<DATE>>>  \u00b7  Content & Programming"

doc.save(OUT)
print(f'Saved: {OUT}')
```

**OUT_PATH format**: `~/Downloads/National_Team_Weekly_Update_M_D_populated.docx` where M_D is month and day digits (e.g. `4_14`).

---

### Step 3 — Confirm

After the script runs successfully, say:
> Done. Your document is saved to `~/Downloads/National_Team_Weekly_Update_M_D_populated.docx`. Open it, review, and edit before sending.

If the script fails, show the error and identify the most likely cause.

---

### Formatting rules — enforce every time

- **One page only.** Content must fit on a single 8.5×11 page. Write concise bullets (1–2 sentences each). Condense rather than exceed the bullet limits.
- **No sub-headers in body sections.** CLUSTER PERFORMANCE HIGHLIGHTS, ACTIVE TEST PERFORMANCE, and CSA & TOOLING UPDATES contain only bullet paragraphs. Never add bold labels like "Engagement Leaders" or "Property Breakdown."
- **Bullet limits**: Cluster Performance = exactly 3. Active Test = exactly 3. CSA = 2–3.
- **Numbers in bullets.** Where the documents have specific numbers (PV counts, percentages, article counts), include them in the bullets.

---

## One-time setup (do this once per machine)

**1. Install Claude Code** if not already installed.

**2. Install python-docx**
```
pip3 install python-docx
```

**3. Save the skill folder** (both files) to:
```
~/.claude/skills/sarah-weekly-update/skill.md
~/.claude/skills/sarah-weekly-update/Template National Team Weekly Update.docx
```

After setup, `/sarah-weekly-update` works in any Claude Code conversation.
'''

with open(dest_file, 'w') as f:
    f.write(content)

print(f'Written: {dest_file}')
